src/gestionFilms/AdminBundle/Entity/film.php
<?php

namespace gestionFilms\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * film
 *
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity
 */
class film
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=1000)
     */
    private $titre;
    
    /**
     * @var string
     *
     * @ORM\Column(name="resume", type="string", length=1500)
     */
    private $resume;
    
    /**
     * @var string
     *
     * @ORM\Column(name="genre", type="string", length=255)
     */
    private $genre;
    
    /**
     * @var string
     *
     * @ORM\Column(name="acteurPrincipal", type="string", length=255)
     */
    private $acteurPrincipal;
    
    /**
     * @var string
     *
     * @ORM\Column(name="acteursescondaires", type="string", length=512)
     */
    private $acteursescondaires;
    
    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=512 , nullable=true)
     */
    private $photo;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="anneeSortie", type="date")
     */
    private $anneeSortie;
    
    /**
     * @var string
     *
     * @ORM\Column(name="langue", type="string", length=255)
     */
    private $langue;
    
    /**
     * @var string
     *
     * @ORM\Column(name="realisateur", type="string", length=255)
     */
    private $realisateur;
    
    /**
     * @var string
     *
     * @ORM\Column(name="duree", type="string", length=255)
     */
    private $duree;
    
    private $file;
    
    private $tempFilename;
    
    
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if (null !== $this->photo) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->photo;
            
            // On réinitialise les valeurs des attributs url et alt
            $this->photo = null;
        }
    }
    
    public function getFile()
    {
        return $this->file;
    }
    
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }
        
        // Et on génère l'attribut photo, à la valeur du nom du fichier sur le PC de l'internaute
        $this->photo = $this->file->getClientOriginalName();
    }
    
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }
        
        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '_' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        
        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move($this->getUploadRootDir(), // Le répertoire de destination
            $this->id . '_' . $this->photo // Le nom du fichier à créer, ici « id.extension »
            );
    }
    
    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '_' . $this->photo;
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }
    
    public function getWebPath()
    {
        return $this->getUploadDir() . '/' . $this->getId() . '_' . $this->getPhoto();
    }
    
    
    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img/film';
    }
    
    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }
    
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set titre
     *
     * @param string $titre
     * @return film
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
        
        return $this;
    }
    
    /**
     * Get titre
     *
     * @return string 
     */
    public function getTitre()
    {
        return $this->titre;
    }
    
    /**
     * Set resume
     *
     * @param string $resume
     * @return film
     */
    public function setResume($resume)
    {
        $this->resume = $resume;
        
        return $this;
    }
    
    /**
     * Get resume
     *
     * @return string 
     */
    public function getResume()
    {
        return $this->resume;
    }
    
    /**
     * Set genre
     *
     * @param string $genre
     * @return film
     */
    public function setGenre($genre)
    {
        $this->genre = $genre;
        
        return $this;
    }
    
    /**
     * Get genre
     *
     * @return string 
     */
    public function getGenre()
    {
        return $this->genre;
    }
    
    /**
     * Set acteurPrincipal
     *
     * @param string $acteurPrincipal
     * @return film
     */
    public function setActeurPrincipal($acteurPrincipal)
    {
        $this->acteurPrincipal = $acteurPrincipal;
        
        return $this;
    }
    
    /**
     * Get acteurPrincipal
     *
     * @return string 
     */
    public function getActeurPrincipal()
    {
        return $this->acteurPrincipal;
    }
    
    /**
     * Set anneeSortie
     *
     * @param \DateTime $anneeSortie
     * @return film
     */
    public function setAnneeSortie($anneeSortie)
    {
        $this->anneeSortie = $anneeSortie;
        
        return $this;
    }
    
    /**
     * Get anneeSortie
     *
     * @return \DateTime 
     */
    public function getAnneeSortie()
    {
        return $this->anneeSortie;
    }
    
    /**
     * Set langue
     *
     * @param string $langue
     * @return film
     */
    public function setLangue($langue)
    {
        $this->langue = $langue;
        
        return $this;
    }
    
    /**
     * Get langue
     *
     * @return string 
     */
    public function getLangue()
    {
        return $this->langue;
    }
    
    /**
     * Set realisateur
     *
     * @param string $realisateur
     * @return film
     */
    public function setRealisateur($realisateur)
    {
        $this->realisateur = $realisateur;
        
        return $this;
    }
    
    /**
     * Get realisateur
     *
     * @return string 
     */
    public function getRealisateur()
    {
        return $this->realisateur;
    }
    
    /**
     * Set acteursescondaires
     *
     * @param string $acteursescondaires
     * @return film
     */
    public function setActeursescondaires($acteursescondaires)
    {
        $this->acteursescondaires = $acteursescondaires;
        
        return $this;
    }
    
    /**
     * Get acteursescondaires
     *
     * @return string 
     */
    public function getActeursescondaires()
    {
        return $this->acteursescondaires;
    }
    
    /**
     * Set photo
     *
     * @param string $photo
     * @return film
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;
        
        return $this;
    }
    
    /**
     * Get photo
     *
     * @return string 
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set duree
     *
     * @param string $duree
     * @return film
     */
    public function setDuree($duree)
    {
        $this->duree = $duree;

        return $this;
    }

    /**
     * Get duree
     *
     * @return string 
     */
    public function getDuree()
    {
        return $this->duree;
    }
}

src/gestionFilms/AdminBundle/Resources/views/accueilUser.html.twig
{% extends "gestionFilmsAdminBundle::base.html.twig" %}
{% block title %} {{ parent() }} | Acceuil {% endblock %}
{% block stylesheets  %}
{{ parent() }}
{% endblock %}
{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">{{ 'page_acceuil.film'|trans }}</h3>
        <br class="clear-fix"/>
        <div id="large_grid" class="wmk_grid">
            {% for entity in entities %}
            <ul>
                <li class="thumbnail">
                    <a href="{{asset(entity.webPath)}}" class="ttip_r" title="{{ entity.titre }}">
                    <img src="{{asset(entity.webPath)}}" alt="" class="ttip_r" title="{{ entity.titre }}" />
                    </a>
                    <p>
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('film_edit' , { 'id':entity.id }) }}" title="{{ 'page_acceuil.modifier'|trans }}"><i class="icon-pencil"></i></a>
                        <a href="{{path('film_delete' , { 'id': entity.id , 'type' : 1 }) }}" title="{{ 'page_acceuil.supprimer'|trans }}"><i class="icon-trash"></i></a>
                        {% else %}
                        <a href="{{ path('afficherFilm' , {'id': entity.id }) }}" title="{{ 'page_acceuil.afficher'|trans }}"><i class="icon-list"></i></a>
                        {% endif %}
                        <span>{{ entity.titre }}</span>
                    </p>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{asset('js/jquery.imagesloaded.min.js')}}"></script>
<script src="{{asset('js/jquery.wookmark.js')}}"></script>
<script src="{{asset('js/gebo_gallery.js')}}"></script>
{% endblock %}

src/gestionFilms/AdminBundle/Resources/views/afficherFilm.html.twig
{% extends "gestionFilmsAdminBundle::base.html.twig" %}
{% block title %} {{ parent() }} | {{ entity.titre }} {% endblock %}
{% block stylesheets  %}
{{ parent() }}
{% endblock %}
{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">Informations détailées d'un film </h3>
        <div class="row-fluid">
            <div class="span12">
                <div class="vcard">
                    <img class="thumbnail" src="{{ asset(entity.webPath)}}" width="100" height="100" alt="" />
                    <ul>
                        <li class="v-heading">
                            {{ entity.titre|upper }}
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.categorie'|trans }}</span>
                            <div class="vcard-item">{{ entity.genre }}</div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.date'|trans }}</span>
                            <div class="vcard-item">{{ entity.anneeSortie|date('d/m/y')}}</div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.duree'|trans }}</span>
                            <div class="vcard-item">{{ entity.duree}} Minutes</div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.realisateur'|trans }}</span>
                            <div class="vcard-item">{{ entity.realisateur }}</div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.langue'|trans }}</span>
                            <div class="vcard-item">
                                <ul class="list_a">
                                    <li>{{ entity.langue}} </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.resume'|trans }}</span>
                            <div class="vcard-item">
                                {{ entity.resume }}
                            </div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.acteurP'|trans }}</span>
                            <div class="vcard-item">
                                {{ entity.acteurPrincipal }}
                            </div>
                        </li>
                        <li>
                            <span class="item-key">{{ 'information.acteursS'|trans }}</span>
                            <div class="vcard-item">
                                {{ entity.acteursescondaires }}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{asset('js/gebo_user_static.js')}}"></script>
{% endblock %}

src/gestionFilms/AdminBundle/Resources/views/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %} Gestion des films {% endblock %}</title>
        {% block stylesheets %}
        <!-- Bootstrap framework -->
        <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.min.css')}}" />
        <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap-responsive.min.css')}}" />
        <!-- gebo blue theme-->
        <link rel="stylesheet" href="{{asset('css/green.css')}}" id="link_theme" />
        <!-- tooltips-->
        <link rel="stylesheet" href="{{asset('lib/qtip2/jquery.qtip.min.css')}}" />
      
        <!-- code prettify -->
        <link rel="stylesheet" href="{{asset('lib/google-code-prettify/prettify.css')}}" />
        <!-- colorbox -->
        <link rel="stylesheet" href="{{asset('lib/colorbox/colorbox.css')}}" />
        <!-- notifications -->
        <link rel="stylesheet" href="{{asset('lib/sticky/sticky.css')}}" />
        <link rel="stylesheet" href="{{asset('img/flags/flags.css')}}" />
        <link rel="stylesheet" href="{{asset('css/style.css')}}" />
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans" />
        <!-- Favicon -->
        <link rel="shortcut icon" href="favicon.ico" />
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="{{asset('css/ie.css') }}" />
        <script src="{{asset('js/ie/html5.js')}}"></script>
        <script src="{{asset('js/ie/respond.min.js')}}"></script>
        <![endif]-->
        {% endblock %}
        <script>
            //* hide all elements & show preloader
            document.getElementsByTagName('html')[0].className = 'js';
        </script>
        <!-- Shared on MafiaShare.net  --><!-- Shared on MafiaShare.net  -->
    </head>
    <body>
        <div id="loading_layer" style="display:none"><img src="{{asset('img/ajax_loader.gif')}}" alt="" /></div>
        <div class="style_switcher">
            <div class="sepH_c">
                <p>Colors:</p>
                <div class="clearfix">
                    <a href="javascript:void(0)" class="style_item jQclr blue_theme style_active" title="blue">blue</a>
                    <a href="javascript:void(0)" class="style_item jQclr dark_theme" title="dark">dark</a>
                    <a href="javascript:void(0)" class="style_item jQclr green_theme" title="green">green</a>
                    <a href="javascript:void(0)" class="style_item jQclr brown_theme" title="brown">brown</a>
                    <a href="javascript:void(0)" class="style_item jQclr eastern_blue_theme" title="eastern_blue">eastern blue</a>
                    <a href="javascript:void(0)" class="style_item jQclr tamarillo_theme" title="tamarillo">tamarillo</a>
                </div>
            </div>
            <div class="sepH_c">
                <p>Backgrounds:</p>
                <div class="clearfix">
                    <span class="style_item jQptrn style_active ptrn_def" title=""></span>
                    <span class="ssw_ptrn_a style_item jQptrn" title="ptrn_a"></span>
                    <span class="ssw_ptrn_b style_item jQptrn" title="ptrn_b"></span>
                    <span class="ssw_ptrn_c style_item jQptrn" title="ptrn_c"></span>
                    <span class="ssw_ptrn_d style_item jQptrn" title="ptrn_d"></span>
                    <span class="ssw_ptrn_e style_item jQptrn" title="ptrn_e"></span>
                </div>
            </div>
            <div class="sepH_c">
                <p>Sidebar position:</p>
                <div class="clearfix">
                    <label class="radio inline"><input type="radio" name="ssw_sidebar" id="ssw_sidebar_left" value="" checked /> Left</label>
                    <label class="radio inline"><input type="radio" name="ssw_sidebar" id="ssw_sidebar_right" value="sidebar_right" /> Right</label>
                </div>
            </div>
        </div>
        <div id="maincontainer" class="clearfix">
            <!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="#"><i class="icon-home icon-white"></i> Gestion des films</a>
                            <ul class="nav user_menu pull-right">
                                <li class="divider-vertical hidden-phone hidden-tablet"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle nav_condensed" data-toggle="dropdown">Traduction<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ path('changerLangue' , {'_locale':'fr'}) }}"><i class="flag-fr"></i> {{ 'page_acceuil.traduction.fr'|trans }}</a></li>
                                        <li><a href="{{ path('changerLangue' , {'_locale':'en'}) }}"><i class="flag-us"></i> {{ 'page_acceuil.traduction.en'|trans }}</a></li>
                                    </ul>
                                </li>
                                <li class="divider-vertical hidden-phone hidden-tablet"></li>
                                <li>
                                    <a href="#"><i class="icon-user icon-white"></i> {{ 'page_acceuil.bienvenue'|trans }} {{app.user.username }}</a>
                                </li>
                            </ul>
                            <a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
                            <span class="icon-align-justify icon-white"></span>
                            </a>
                            <nav>
                                <div class="nav-collapse">
                                    <ul class="nav">
                                        <li>
                                            <a href="{{ path('accueilUser') }}"><i class="icon-home icon-white"></i> {{ 'page_acceuil.Acceuil'|trans }}</a>
                                        </li>
                                        {% if is_granted('ROLE_ADMIN') %}
                                        <li>
                                            <a href="{{path('film')}}"><i class="icon-edit icon-white"></i> {{ 'page_acceuil.gestion_film' |trans }}</a>
                                        </li>
                                        {% endif %}
                                        <li>
                                            <a href="{{path('fos_user_profile_show') }}"><i class="icon-picture icon-white"></i> {{ 'page_acceuil.Profil'|trans }}</a>
                                        </li>
                                        <li>
                                            <a href="{{path('recherhceFilm') }}"><i class="icon-search icon-white"></i> {{ 'page_acceuil.reche'|trans }}</a>
                                        </li>
                                        <li>
                                            <a href="{{path('fos_user_security_logout')}}"><i class="icon-off icon-white"></i> {{ 'page_acceuil.deconnexion'|trans}}</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>
            <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <!-- sidebar -->
            <a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Hide Sidebar">Sidebar switch</a>
            <div class="sidebar">
                <div class="antiScroll">
                    <div class="antiscroll-inner">
                        <div class="antiscroll-content">
                        </div>
                    </div>
                </div>
            </div>
            {% block javascripts %}
            <script src="{{asset('js/jquery.min.js')}}"></script>
            <!-- smart resize event -->
            <script src="{{asset('js/jquery.debouncedresize.min.js')}}"></script>
            <!-- hidden elements width/height -->
            <script src="{{asset('js/jquery.actual.min.js')}}"></script>
            <!-- js cookie plugin -->
            <script src="{{asset('js/jquery.cookie.min.js')}}"></script>
            <!-- main bootstrap js -->
            <script src="{{asset('bootstrap/js/bootstrap.min.js')}}"></script>
            <!-- tooltips -->
            <script src="{{asset('lib/qtip2/jquery.qtip.min.js')}}"></script>
            <script src="{{asset('lib/sticky/sticky.min.js')}}"></script>
            <script src="{{asset('js/ios-orientationchange-fix.js')}}"></script>
            <script src="{{asset('lib/colorbox/jquery.colorbox.min.js')}}"></script>
            <!-- scrollbar -->
            <script src="{{asset('lib/antiscroll/antiscroll.js')}}"></script>
            <script src="{{asset('lib/antiscroll/jquery-mousewheel.js')}}"></script>
            <!-- common functions -->
            <script src="{{asset('js/gebo_common.js')}}"></script>
            <script>
                $(document).ready(function() {
                	setTimeout('$("html").removeClass("js")',1000);
                });
            </script>
            {% endblock %}
        </div>
    </body>
</html>

src/gestionFilms/AdminBundle/Resources/views/flux.xml.twig
<?xml version="1.0"?>
<rss version="2.0">
    <channel>
        <title>Liste des derniers films enregistrés</title>
        <link href="{{ url('accueilUser') }}"/>
        <description>affichage des nouveaux films</description>
        <language>fr-fr</language>
        <copyright>Copyright 2014</copyright>
        <managingEditor>{{ app.user.email }}</managingEditor>
        <pubDate>{{ "now"|date("m/d/Y") }}</pubDate>
        {% for entity in entities %}
        <item>
            <title>{{ entity.titre }}</title>
            <description>{{ entity.resume }}</description>           
            <link> {{ path('afficherFilm' , {'id':entity.id }) }}</link>            
            <guid>{{ feedId }}</guid>
        </item>
        {% endfor %}
    </channel>
</rss>

src/gestionFilms/AdminBundle/Resources/views/resultat.html.twig
<h3 class="heading">{{ 'information.label'|trans }}</h3>
<div class="row-fluid">
    <div class="span12">
        <div class="vcard">
            <img class="thumbnail" src="{{ asset(entity.webPath)}}" width="100" height="100" alt="" />
            <ul>
                <li class="v-heading">
                    {{ entity.titre|upper }}
                </li>
                <li>
                    <span class="item-key">{{ 'information.categorie'|trans }}</span>
                    <div class="vcard-item">{{ entity.genre }}</div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.date'|trans }}</span>
                    <div class="vcard-item">{{ entity.anneeSortie|date('d/m/y')}}</div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.duree'|trans }}</span>
                    <div class="vcard-item">{{ entity.duree}} Minutes</div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.realisateur'|trans }}</span>
                    <div class="vcard-item">{{ entity.realisateur }}</div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.langue'|trans }}</span>
                    <div class="vcard-item">
                        <ul class="list_a">
                            <li>{{ entity.langue}} </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.resume'|trans }}</span>
                    <div class="vcard-item">
                        {{ entity.resume }}
                    </div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.acteurP'|trans }}</span>
                    <div class="vcard-item">
                        {{ entity.acteurPrincipal }}
                    </div>
                </li>
                <li>
                    <span class="item-key">{{ 'information.acteursS'|trans }}</span>
                    <div class="vcard-item">
                        {{ entity.acteursescondaires }}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>